# Generated by Django 3.1.1 on 2020-09-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MMANews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('thumbnail_url', models.CharField(max_length=250)),
                ('img_url', models.CharField(max_length=250)),
            ],
        ),
    ]
